import type { Language } from "./anatomy";

export const copy = {
  zh: {
    brandKicker: "OPEN ANATOMY",
    brandName: "开放解剖工作室",
    explore: "探索",
    library: "器官库",
    progress: "学习进度",
    sources: "来源与许可",
    theme: "切换明暗主题",
    language: "Switch to English",
    search: "搜索器官、系统或拉丁名",
    allSystems: "全部系统",
    favorites: "我的收藏",
    favoriteAdd: "收藏这个器官",
    favoriteRemove: "取消收藏",
    modelStage: "三维标本台",
    dragHint: "拖动旋转 · 滚轮缩放 · 点击模型结构",
    rotate: "自动旋转",
    labels: "结构标注",
    section: "剖切模式",
    sectionDepth: "剖切深度",
    clearFocus: "清除结构焦点",
    reset: "重置视角",
    selectedStructure: "当前结构",
    selectStructure: "点击模型结构，查看对象名称并突出显示。",
    overview: "结构概览",
    keyFacts: "关键事实",
    functions: "主要功能",
    openQuiz: "开始 1 分钟测验",
    sourceNote: "内容依据 OpenStax 与美国国立医学图书馆资料整理。",
    educational: "仅用于解剖学习，不替代医学诊断或专业建议。",
    loading: "正在装配三维器官",
    quiz: "快速测验",
    quizHint: "选择一个答案，系统会立即解释。",
    check: "检查答案",
    correct: "回答正确",
    incorrect: "再看一次",
    nextOrgan: "下一个器官",
    close: "关闭",
    sourceTitle: "来源、许可与边界",
    sourceLead: "模型与知识层分开追踪，让每一项内容都能被审计。",
    modelLicense: "模型许可",
    codeLicense: "代码许可",
    contentLicense: "内容说明",
    codeLicenseText: "本项目 clean-room 源码采用 MIT 许可。",
    modelLicenseText: "3D 模型来自 Human Reference Atlas，采用 CC BY 4.0。",
    contentLicenseText: "双语文字为本项目基于公开教育资料编写的摘要，请始终回到原始来源核验。",
    openSource: "打开权威来源",
    visited: "已探索",
    of: "项，共",
    keyboard: "快捷键：J / K 切换器官，空格暂停旋转",
    noResults: "没有找到匹配器官",
    favoritesEmpty: "收藏器官后会在这里形成你的复习列表。",
    attribution: "3D 器官 © Human Reference Atlas (CC BY 4.0), HuBMAP",
    currentOrgan: "当前器官",
  },
  en: {
    brandKicker: "OPEN ANATOMY",
    brandName: "Open Anatomy Studio",
    explore: "Explore",
    library: "Organ library",
    progress: "Learning progress",
    sources: "Sources and licenses",
    theme: "Toggle light or dark theme",
    language: "切换到中文",
    search: "Search organ, system, or Latin name",
    allSystems: "All systems",
    favorites: "My favorites",
    favoriteAdd: "Save this organ",
    favoriteRemove: "Remove from favorites",
    modelStage: "3D specimen stage",
    dragHint: "Drag to rotate · Scroll to zoom · Click a model structure",
    rotate: "Auto rotate",
    labels: "Structure labels",
    section: "Section mode",
    sectionDepth: "Section depth",
    clearFocus: "Clear structure focus",
    reset: "Reset view",
    selectedStructure: "Selected structure",
    selectStructure: "Click a model structure to reveal its object name and highlight it.",
    overview: "Structural overview",
    keyFacts: "Key facts",
    functions: "Primary functions",
    openQuiz: "Start a 1 minute quiz",
    sourceNote: "Content is synthesized from OpenStax and the U.S. National Library of Medicine.",
    educational: "For anatomy learning only. Not a substitute for diagnosis or professional medical advice.",
    loading: "Assembling the 3D organ",
    quiz: "Quick quiz",
    quizHint: "Choose one answer and get an immediate explanation.",
    check: "Check answer",
    correct: "Correct",
    incorrect: "Take another look",
    nextOrgan: "Next organ",
    close: "Close",
    sourceTitle: "Sources, licenses, and boundaries",
    sourceLead: "Models and knowledge are tracked separately so every layer remains auditable.",
    modelLicense: "Model license",
    codeLicense: "Code license",
    contentLicense: "Content note",
    codeLicenseText: "The clean-room source code in this project is licensed under MIT.",
    modelLicenseText: "3D models come from the Human Reference Atlas under CC BY 4.0.",
    contentLicenseText: "Bilingual copy is an original summary based on public educational references. Verify important facts against the primary sources.",
    openSource: "Open authoritative source",
    visited: "Explored",
    of: "of",
    keyboard: "Shortcuts: J / K changes organ, Space pauses rotation",
    noResults: "No matching organs",
    favoritesEmpty: "Save organs to build a personal review list here.",
    attribution: "3D organs © Human Reference Atlas (CC BY 4.0), HuBMAP",
    currentOrgan: "Current organ",
  },
} as const satisfies Record<Language, Record<string, string>>;

export type Copy = (typeof copy)[Language];
